amcl:
  ros__parameters:
    use_sim_time: true
    min_particles: 500
    max_particles: 5000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /home/parth/Superbot_ws/maps/my_map.yaml  # Adjust path to your map
    frame_id: map

# Global costmap parameters
costmap:
  ros__parameters:
    robot_radius: 0.2
    update_frequency: 5.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_footprint
    rolling_window: true
    resolution: 0.05
    footprint:
      - [-0.2, -0.2]
      - [0.2, -0.2]
      - [0.2, 0.2]
      - [-0.2, 0.2]
