slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_file_name: ""
    map_update_interval: 5.0
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    resolution: 0.05
    publish_to_frame: map
